version: '2'
services:
  learningspringboot-app:
    image: learningspringboot
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://learningspringboot-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=LearningSpringBoot
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  learningspringboot-mongodb:
    extends:
      file: mongodb.yml
      service: learningspringboot-mongodb
